# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-Prog
version:      0.01
version_from: lib/SWISH/Prog.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.01
    Data::Dumper:                  0.01
    File::Basename:                0.01
    File::Find:                    0.01
    File::Slurp:                   0.01
    File::stat:                    0.01
    File::Temp:                    0.01
    File::Type:                    0.01
    Search::Tools:                 0.01
    SWISH::Filter:                 0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
