---
abstract: 'information retrieval application framework'
author:
  - 'Peter Karman, <perl@peknet.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SWISH-Prog
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  DBI: 0
  File::Find: 0
  JSON: 2
  Mail::Box: 0
  SWISH::API::Object: 0.13
  Term::ProgressBar: 0
  URI: 0
  WWW::Mechanize: 0
  YAML::Syck: 0.72
requires:
  Config::General: 2.31
  Data::Dump: 0
  File::Basename: 0
  File::Slurp: 0
  File::Temp: 0
  MIME::Types: 0
  Path::Class: 0
  Rose::DateTime: 0
  Rose::ObjectX::CAF: 0
  SWISH::Filter: 0.15
  Scalar::Util: 0
  Search::Query: 0.17
  Search::Tools: 0.43
  Test::More: 0
  Time::HiRes: 0
  XML::Simple: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-Prog
  homepage: http://dev.swish-e.org/wiki/perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.swish-e.org/perl/SWISH-Prog/
version: 0.48
