--- #YAML:1.0
name:                SWISH-Prog
version:             0.21
abstract:            information retrieval application framework
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Config::General:               2.31
    Data::Dump:                    0
    File::Basename:                0
    File::Slurp:                   0
    File::Temp:                    0
    MIME::Types:                   0
    Path::Class:                   0
    Scalar::Util:                  0
    Search::Tools:                 0.16
    SWISH::Filter:                 0.09
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
