# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-Prog
version:      0.06
version_from: lib/SWISH/Prog.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.01
    Config::General:               2.31
    Data::Dump:                    0.01
    File::Basename:                0.01
    File::Copy:                    0.01
    File::Temp:                    0.01
    IO::All:                       0.01
    MIME::Types:                   0.01
    Search::Tools:                 0.01
    SWISH::Filter:                 0.07
    YAML::Syck:                    0.72

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
